/**
 * The licence of every source a recipe uses (spec 08 §5.1). Each folder of
 * sources has a `credits.json`: audio-src/library/<origin>/credits.json for
 * a library, audio-src/generated/credits.json for what an AI made. Its
 * top-level fields hold for every file of the folder, and `files` holds
 * each file's own (a Freesound file has its author and link; a generated
 * one, the text it was asked with and the model):
 *
 *   { "origin": "Kenney · Impact Sounds", "author": "Kenney", "license": "CC0 1.0",
 *     "url": "https://kenney.nl/assets/impact-sounds", "files": { "x.ogg": { … } } }
 *
 * audio:gen writes docs/AUDIO-CREDITS.md from them, and assets:check fails
 * on a source with no complete record.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { basename, resolve } from 'node:path';
import { parseSoundRecipes, sourcesOf } from './recipes';

export interface Credit {
  origin: string;
  author: string;
  license: string;
  url: string;
  /** Generated by an AI (§5.3): what it was asked, and with which model. */
  prompt?: string;
  model?: string;
}

/** A credits.json: the folder's fields, and each file's own. */
export interface CreditsFile extends Partial<Credit> {
  files?: Record<string, Partial<Credit>>;
}

/** Where a source's record lives: its folder's credits.json, under the file's path from that folder. */
export function creditsHome(source: string): { folder: string; file: string } | null {
  const parts = source.split('/');
  if (parts[0] === 'library' && parts.length >= 3) return { folder: `library/${parts[1] ?? ''}`, file: parts.slice(2).join('/') };
  if (parts[0] === 'generated' && parts.length >= 2) return { folder: 'generated', file: parts.slice(1).join('/') };
  // The tracks the user picks (§7): CC0 or a licence like it, each with its record.
  if (parts[0] === 'music' && parts.length >= 2) return { folder: 'music', file: parts.slice(1).join('/') };
  return null;
}

const FIELDS = ['origin', 'author', 'license', 'url'] as const;

/** Reads the records of the sources under audio-src/ (`root`); each credits.json is read once. */
export class Credits {
  private readonly folders = new Map<string, CreditsFile | string>();

  constructor(private readonly root: string) {}

  /** A source's record (its path from audio-src/), or what is wrong with it. */
  of(source: string): { credit: Credit } | { problem: string } {
    const home = creditsHome(source);
    if (!home) return { problem: `${source}: las fuentes van en library/<origen>/ o en generated/` };
    const folder = this.folder(home.folder);
    if (typeof folder === 'string') return { problem: `${source}: ${folder}` };
    const merged: Partial<Credit> = { ...folder, ...folder.files?.[home.file] };
    const missing = FIELDS.filter((f) => typeof merged[f] !== 'string' || merged[f].trim() === '');
    if (home.folder === 'generated') for (const f of ['prompt', 'model'] as const) if (!merged[f]) missing.push(f as never);
    if (missing.length > 0) return { problem: `${source}: sin ficha completa en audio-src/${home.folder}/credits.json (falta ${missing.join(', ')})` };
    const credit = merged as Credit;
    // The repository is public: from a library, only CC0 (§5.1).
    if (home.folder.startsWith('library/') && !/\bCC0\b/i.test(credit.license)) return { problem: `${source}: licencia «${credit.license}»; de las bibliotecas solo vale CC0` };
    return { credit: { origin: credit.origin, author: credit.author, license: credit.license, url: credit.url, ...(credit.prompt ? { prompt: credit.prompt, model: credit.model } : {}) } };
  }

  private folder(folder: string): CreditsFile | string {
    const cached = this.folders.get(folder);
    if (cached !== undefined) return cached;
    const path = resolve(this.root, folder, 'credits.json');
    let value: CreditsFile | string;
    if (!existsSync(path)) value = `falta audio-src/${folder}/credits.json`;
    else {
      try {
        value = JSON.parse(readFileSync(path, 'utf8')) as CreditsFile;
      } catch (err) {
        value = `audio-src/${folder}/credits.json no es JSON válido (${(err as Error).message})`;
      }
    }
    this.folders.set(folder, value);
    return value;
  }
}

export interface CreditRow {
  source: string;
  credit: Credit;
  /** The sounds whose recipes use it. */
  sounds: string[];
}

const cell = (text: string): string => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');

/** docs/AUDIO-CREDITS.md: one row per source file used. */
export function creditsMarkdown(rows: readonly CreditRow[]): string {
  const sorted = [...rows].sort((a, b) => a.source.localeCompare(b.source));
  const generated = sorted.filter((r) => r.credit.prompt);
  return [
    '# Créditos de audio',
    '',
    'Generado por `npm run audio:gen` a partir de los `credits.json` de `audio-src/` (spec 08 §5.1). Una fila por archivo de origen que usa alguna receta de `audio-src/recipes/`. No lo edites a mano: cambia la ficha y vuelve a generar.',
    '',
    '| Archivo de origen | Origen | Autor | Licencia | Enlace | Sonidos |',
    '|---|---|---|---|---|---|',
    ...sorted.map((r) => `| \`${cell(r.source)}\` | ${cell(r.credit.origin)} | ${cell(r.credit.author)} | ${cell(r.credit.license)} | ${cell(r.credit.url)} | ${cell(r.sounds.join(', '))} |`),
    ...(generated.length > 0
      ? ['', '## Generados por IA', '', '| Archivo | Modelo | Texto |', '|---|---|---|', ...generated.map((r) => `| \`${cell(r.source)}\` | ${cell(r.credit.model ?? '')} | ${cell(r.credit.prompt ?? '')} |`)]
      : []),
    '',
  ].join('\n');
}

/** Every source the recipes in `recipesDir` use, with the sounds that use it. */
export function recipeSources(recipesDir: string): Map<string, string[]> {
  const used = new Map<string, string[]>();
  const names = existsSync(recipesDir) ? readdirSync(recipesDir).filter((f) => f.endsWith('.json')).sort() : [];
  for (const name of names) {
    const id = basename(name, '.json');
    const recipes = parseSoundRecipes(JSON.parse(readFileSync(resolve(recipesDir, name), 'utf8')), name);
    for (const candidate of Object.values(recipes.candidates)) {
      for (const recipe of [...candidate.variants, ...candidate.shine]) {
        for (const source of sourcesOf(recipe)) {
          const sounds = used.get(source) ?? [];
          if (!sounds.includes(id)) sounds.push(id);
          used.set(source, sounds);
        }
      }
    }
  }
  return used;
}
